guide :
	latex user_guide 
	latex user_guide 
	latex user_guide
	dvips -Ppdf -o user_guide.ps user_guide.dvi
	ps2pdf user_guide.ps ../user_guide.pdf
 
clean :
	/bin/rm -f *.aux *.log *.lot *.lof *.toc *.dvi *.bak *~ *.bbl *.blg user_guide.ps


