language: python
python:
    - "3.6"
addons:
  apt:
    packages:
        - gfortran 
        - libblas-dev 
        - liblapack-dev 
        - openmpi-bin
        - libopenmpi-dev
env:
   - RUNTESTS=false RUNPRECOMMIT=true
## Use these two lines instead of the other two if you want increased output
#   - RUNTESTS=true W90BINARYPARALLEL=false W90VERBOSETESTS=true
#   - RUNTESTS=true W90BINARYPARALLEL=true W90VERBOSETESTS=true
   - RUNTESTS=true RUNPRECOMMIT=false W90BINARYPARALLEL=false
   - RUNTESTS=true RUNPRECOMMIT=false W90BINARYPARALLEL=true
install:
# Install Wannier
    - if [ "$RUNPRECOMMIT" == "true" ] ; then ./test-suite/install_precommit.sh ; fi
    - if [ "$RUNTESTS" == "true" ] ; then ./test-suite/tools/configure_travis_compilation.sh ; fi
    - if [ "$RUNTESTS" == "true" ] ; then make -j default w90chk2chk libs ; fi
script:
    - if [ "$RUNPRECOMMIT" == "true" ] ; then ./test-suite/tools/run_precommit.sh ; fi
    - if [ "$RUNTESTS" == "true" ] ; then ./test-suite/tools/run_tests_travis.sh ; fi
git:
  depth: 3
after_success:
  - bash <(curl -s https://codecov.io/bash)

