language: python
python:
    - "3.6"
addons:
  apt:
    packages:
        - gfortran 
        - libblas-dev 
        - liblapack-dev 
        - openmpi-bin
        - libopenmpi-dev
env:
## Use these two lines instead of the other two if you want increased output
#   - W90BINARYPARALLEL=false W90VERBOSETESTS=true
#   - W90BINARYPARALLEL=true W90VERBOSETESTS=true
   - W90BINARYPARALLEL=false
   - W90BINARYPARALLEL=true
install:
# Install Wannier
    - ./test-suite/tools/configure_travis_compilation.sh
    - make -j default w90chk2chk libs
script:
    - ./test-suite/tools/run_tests_travis.sh
git:
  depth: 3
after_success:
  - bash <(curl -s https://codecov.io/bash)

