#!/usr/bin/env python3
"""Generate the synthetic physics-pinning inputs for the wannier_decompose
test-suite tests

  testw90_decompose_sphere : a single "Wannier function" that is an isotropic
      Gaussian u(r) = N exp(-|r - c|^2 / (2 sigma^2)) about a deliberately
      non-grid-aligned centre c. Its density is pure l=0, so every l >= 1
      coefficient of the decomposition is ~0 (up to a tiny, deterministic
      grid-discretisation residue). This pins the physics (in particular the
      grid-origin/index convention of decompose_project) rather than mere
      reproducibility.

  testw90_decompose_l2 : a single d_z2-like "Wannier function"
      u(r) = N (3 z'^2 - r'^2) exp(-r'^2 / (2 sigma^2)), r' = r - c.
      Its density contains ONLY (l, m) = (0,0), (2,0) and (4,0) components:
      all odd-l and all m /= 0 coefficients are ~0, and the l=2 / l=4
      values are analytically known (see check_decompose_synthetic.py).

Both systems are gamma-only (mp_grid = 1 1 1), num_bands = num_wann = 1,
with an identity .amn and num_iter = 0 so that the U matrix stays 1 and the
"Wannier function" is exactly the synthetic u(r) written to UNK00001.1.
The .mmn overlaps M(b) = <u| e^{-i b.r} |u> are computed numerically on the
grid for exactly the b-vectors wannier90 selects (obtained by running
`wannier90.x -pp`), so the WF centre wannier90 reports equals the true
Gaussian centre: for a density that is even about c, M(b) = e^{-i b.c} |M(b)|
exactly, hence Im ln M(b) = -b.c and the standard centre formula recovers c.

Everything is deterministic (no random numbers, no timestamps): regenerating
the inputs reproduces them bit-for-bit. The generated files are nevertheless
committed, so the tests are self-contained and this script only needs to be
re-run if the synthetic systems are changed.

Usage:
    python3 generate_decompose_synthetic.py --w90 /path/to/wannier90.x \
            [--testdir /path/to/test-suite/tests]
"""

import argparse
import os
import shutil
import subprocess

import numpy as np

# ----------------------------------------------------------------------
# System definitions (shared)
# ----------------------------------------------------------------------
L = 8.0    # cubic cell side (Angstrom)
NG = 24    # real-space grid points per side

SYSTEMS = {
    'testw90_decompose_sphere': {
        'seed': 'sphere',
        'kind': 'sphere',
        'sigma': 0.8,                          # Angstrom
        'centre': (3.2117, 2.8331, 3.4569),    # Angstrom, off-grid (h = 1/3)
        'n_max': 3,
        'l_max': 2,
        'r_min': 2.5,
        'r_max': 4.0,
        'r_cut': 3.8,
        'comment': [
            '! Synthetic physics-pinning test for wannier_decompose.',
            '! Single "WF" = isotropic Gaussian about a non-grid-aligned centre:',
            '! the density is pure l=0, so all l>=1 coefficients must vanish',
            '! (up to a tiny grid-discretisation residue). Identity amn +',
            '! num_iter=0 keep U=1, so the WF is exactly the UNK orbital.',
            '! Inputs generated by tools/generate_decompose_synthetic.py.',
        ],
    },
    'testw90_decompose_l2': {
        'seed': 'dz2',
        'kind': 'dz2',
        'sigma': 0.8,
        'centre': (3.3579, 3.1259, 2.9873),
        'n_max': 2,
        'l_max': 4,
        'r_min': 2.5,
        'r_max': 4.0,
        'r_cut': 3.8,
        'comment': [
            '! Synthetic physics-pinning test for wannier_decompose.',
            '! Single "WF" = d_z2-like orbital u ~ (3z\'^2 - r\'^2) exp(-r\'^2/2s^2)',
            '! about a non-grid-aligned centre: |u|^2 contains only',
            '! (l,m) = (0,0), (2,0), (4,0), so all odd-l and m/=0 coefficients',
            '! must vanish and the (2,0)/(4,0) values are analytically known.',
            '! Inputs generated by tools/generate_decompose_synthetic.py.',
        ],
    },
}

UNK_FMT = '{0: .10E}  0.0'   # real part, imaginary part is exactly zero


def grid_coords():
    """1-based grid point (i) at fractional coordinate (i-1)/NG (the
    wannier90 UNK / plot_build_wannier_grid convention)."""
    f = np.arange(NG) / NG          # (i-1)/NG for i = 1..NG
    x = f * L
    return np.meshgrid(x, x, x, indexing='ij')   # u[ix, iy, iz]


def build_u(kind, sigma, centre):
    """Synthetic orbital on the grid, periodised over 3^3 images."""
    X, Y, Z = grid_coords()
    u = np.zeros_like(X)
    for Rx in (-1, 0, 1):
        for Ry in (-1, 0, 1):
            for Rz in (-1, 0, 1):
                dx = X - centre[0] - Rx * L
                dy = Y - centre[1] - Ry * L
                dz = Z - centre[2] - Rz * L
                r2 = dx * dx + dy * dy + dz * dz
                g = np.exp(-r2 / (2.0 * sigma ** 2))
                if kind == 'sphere':
                    u += g
                elif kind == 'dz2':
                    u += (3.0 * dz * dz - r2) * g
                else:
                    raise ValueError(kind)
    # Normalize sum |u|^2 dV = 1 (cosmetic: wannier90 renormalizes anyway)
    dv = (L / NG) ** 3
    u /= np.sqrt(np.sum(u * u) * dv)
    return u


def roundtrip_unk(u):
    """Round u through the exact text written to UNK00001.1, so that all
    subsequent numbers (mmn overlaps, analytic checks) are computed from
    the values wannier90 actually reads."""
    flat = u.transpose(2, 1, 0).ravel()          # x contiguous
    lines = [UNK_FMT.format(v) for v in flat]
    rounded = np.array([float(l.split()[0]) for l in lines])
    u_r = rounded.reshape(NG, NG, NG).transpose(2, 1, 0)
    return u_r, lines


def write_unk(dirname, lines):
    with open(os.path.join(dirname, 'UNK00001.1'), 'w') as f:
        f.write('  {0}  {0}  {0}    1    1\n'.format(NG))
        f.write('\n'.join(lines))
        f.write('\n')


def write_win(dirname, sysdef, pp=False):
    seed = sysdef['seed']
    c = sysdef['centre']
    lines = list(sysdef['comment'])
    lines += [
        '',
        'num_wann    = 1',
        'num_iter    = 0',
        '',
        'begin unit_cell_cart',
        'ang',
        ' {0:.1f}  0.0  0.0'.format(L),
        '  0.0 {0:.1f}  0.0'.format(L),
        '  0.0  0.0 {0:.1f}'.format(L),
        'end unit_cell_cart',
        '',
        '! Dummy atom marking the true orbital centre',
        'begin atoms_cart',
        'ang',
        'H  {0:.4f}  {1:.4f}  {2:.4f}'.format(*c),
        'end atoms_cart',
        '',
        'begin projections',
        'random',
        'end projections',
        '',
        'mp_grid : 1 1 1',
        '',
        'begin kpoints',
        '0.0 0.0 0.0',
        'end kpoints',
        '',
        'wvfn_formatted = .true.',
        '',
        'wannier_decompose = true',
        'decompose_n_max   = {0}'.format(sysdef['n_max']),
        'decompose_l_max   = {0}'.format(sysdef['l_max']),
        'decompose_r_min   = {0}'.format(sysdef['r_min']),
        'decompose_r_max   = {0}'.format(sysdef['r_max']),
        'decompose_r_cut   = {0}'.format(sysdef['r_cut']),
    ]
    with open(os.path.join(dirname, seed + '.win'), 'w') as f:
        f.write('\n'.join(lines) + '\n')


def read_nnkp_bvectors(dirname, seed):
    """Parse the nnkpts block of seed.nnkp: records (ik, ikp, G)."""
    fname = os.path.join(dirname, seed + '.nnkp')
    with open(fname) as f:
        lines = [l.strip() for l in f]
    i0 = lines.index('begin nnkpts')
    nntot = int(lines[i0 + 1])
    recs = []
    for l in lines[i0 + 2:i0 + 2 + nntot]:
        w = l.split()
        recs.append((int(w[0]), int(w[1]), int(w[2]), int(w[3]), int(w[4])))
    return recs


def write_mmn(dirname, seed, u, recs):
    """M(b) = sum_r |u(r)|^2 e^{-i b.r} dV / sum_r |u(r)|^2 dV for each
    nnkp record; at gamma with one k-point b = G . B, B = (2 pi / L) I."""
    X, Y, Z = grid_coords()
    rho = u * u
    norm = rho.sum()
    header = 'Synthetic gamma-only overlaps (generate_decompose_synthetic.py)'
    out = [header, '    1    1    {0}'.format(len(recs))]
    for (ik, ikp, g1, g2, g3) in recs:
        b = 2.0 * np.pi / L * np.array([g1, g2, g3], dtype=float)
        phase = np.exp(-1j * (b[0] * X + b[1] * Y + b[2] * Z))
        m = (rho * phase).sum() / norm
        out.append('    {0}    {1}    {2}    {3}    {4}'.format(ik, ikp, g1, g2, g3))
        out.append('  {0: .12f}  {1: .12f}'.format(m.real, m.imag))
    with open(os.path.join(dirname, seed + '.mmn'), 'w') as f:
        f.write('\n'.join(out) + '\n')


def write_amn(dirname, seed):
    with open(os.path.join(dirname, seed + '.amn'), 'w') as f:
        f.write('Identity projection (generate_decompose_synthetic.py)\n')
        f.write('           1           1           1\n')
        f.write('    1    1    1    1.000000000000    0.000000000000\n')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--w90', required=True, help='path to a wannier90.x binary '
                   '(used only for -pp, to obtain the b-vector list)')
    p.add_argument('--testdir', default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'tests'))
    args = p.parse_args()
    w90 = os.path.abspath(args.w90)

    for dirname, sysdef in SYSTEMS.items():
        seed = sysdef['seed']
        d = os.path.abspath(os.path.join(args.testdir, dirname))
        os.makedirs(d, exist_ok=True)
        print('=== {0} (seed {1}) ==='.format(dirname, seed))

        write_win(d, sysdef)

        # b-vectors exactly as wannier90 will choose them
        subprocess.run([w90, '-pp', seed], cwd=d, check=True,
                       stdout=subprocess.DEVNULL)
        recs = read_nnkp_bvectors(d, seed)
        print('  nnkp b-vector records:', recs)
        os.remove(os.path.join(d, seed + '.nnkp'))
        for junk in (seed + '.wout',):
            path = os.path.join(d, junk)
            if os.path.exists(path):
                os.remove(path)

        u = build_u(sysdef['kind'], sysdef['sigma'], sysdef['centre'])
        u, lines = roundtrip_unk(u)
        write_unk(d, lines)
        write_mmn(d, seed, u, recs)
        write_amn(d, seed)

        # Predicted WF centre from the written overlaps (cubic cell:
        # w_b = 1/(2 b^2), centre = -sum_b w_b b Im ln M(b))
        X, Y, Z = grid_coords()
        rho = u * u
        norm = rho.sum()
        centre = np.zeros(3)
        for (ik, ikp, g1, g2, g3) in recs:
            b = 2.0 * np.pi / L * np.array([g1, g2, g3], dtype=float)
            phase = np.exp(-1j * (b[0] * X + b[1] * Y + b[2] * Z))
            m = (rho * phase).sum() / norm
            centre += -1.0 / (2.0 * b @ b) * b * np.log(m).imag
        print('  true centre     :', np.array(sysdef['centre']))
        print('  centre from M(b):', centre)


if __name__ == '__main__':
    main()
