"""pytest configuration for the Wannier90 regression suite.

Adds the command-line options, discovers the tests from tests/*/test.yaml, and provides the
fixtures the single generic test function needs.
"""

import os
import shutil
from pathlib import Path

import pytest

from w90testlib.case import discover_cases
from w90testlib.executables import resolve as resolve_executables
from w90testlib.execute import RunOptions, execute_case
from w90testlib.profiles import load_profiles
from w90testlib.runner import DEFAULT_MPI_LAUNCHER

TEST_SUITE = Path(__file__).parent.resolve()
TESTS_DIR = TEST_SUITE / "tests"
PROFILES_FILE = TEST_SUITE / "profiles.yaml"
REGRESSION_MODULE = TESTS_DIR / "test_regression.py"

#: Markers this suite uses, as "name: description" lines.  Registered in pytest_configure
#: rather than in pytest.ini, because pytest only reads pytest.ini when it picks test-suite/
#: as its rootdir; conftest.py is loaded either way, so the markers are always known.
MARKERS = (
    "wannier90: tests driving wannier90.x (directories testw90_*)",
    "postw90: tests driving postw90.x (directories testpostw90_*)",
    "checkpoint: checkpoint write/read round-trip tests",
    "parallel: tests that only make sense under MPI (directories partest*)",
    "serial: tests that always run serially, even with --nprocs",
)

#: Per-test outcome of --update-benchmarks: name -> whether the reference changed.
UPDATED_BENCHMARKS = pytest.StashKey[dict]()

#: Test directories named directly on the command line, e.g. `pytest tests/testw90_example01`.
#: Collected by pytest_load_initial_conftests and applied in pytest_generate_tests.
_DIRECT_SELECTION: list[str] = []


# --- options -----------------------------------------------------------------------------

def pytest_addoption(parser):
    group = parser.getgroup("wannier90", "Wannier90 regression suite")
    group.addoption("--wannier90-exe", default=os.environ.get("W90_EXE"),
                    help="path to wannier90.x [env: W90_EXE]")
    group.addoption("--postw90-exe", default=os.environ.get("POSTW90_EXE"),
                    help="path to postw90.x [env: POSTW90_EXE]")
    group.addoption("--w90chk2chk-exe", default=os.environ.get("W90CHK2CHK_EXE"),
                    help="path to w90chk2chk.x [env: W90CHK2CHK_EXE]")
    group.addoption("--nprocs", type=int, default=0, metavar="N",
                    help="run each test under MPI with N processes (0 = serial, no launcher)")
    group.addoption("--mpi-launcher", default=DEFAULT_MPI_LAUNCHER, metavar="TEMPLATE",
                    help=f"parallel launch template, {{nprocs}} substituted "
                         f"(default: {DEFAULT_MPI_LAUNCHER!r})")
    group.addoption("--workdir", default=None, metavar="PATH",
                    help="run tests under PATH instead of a temporary directory; implies "
                         "--keep-workdir")
    group.addoption("--keep-workdir", action="store_true",
                    help="do not clean up work directories after the run")
    group.addoption("--update-benchmarks", action="store_true",
                    help="run the tests and overwrite the reference files with the output "
                         "instead of comparing")
    group.addoption("--allow-parallel-update", action="store_true",
                    help="permit --update-benchmarks together with --nprocs")


def pytest_configure(config):
    """Let `pytest tests/testw90_example01` select that one test.

    A test directory holds inputs, not a test module, so pytest would collect nothing from
    it.  Rewrite such arguments to the regression module and remember the names, which
    pytest_generate_tests then uses to narrow the parametrisation.
    """
    for marker in MARKERS:
        config.addinivalue_line("markers", marker)

    rewritten = []
    for arg in config.args:
        path = Path(arg)
        if path.is_dir() and (path / "test.yaml").is_file():
            _DIRECT_SELECTION.append(path.name)
        else:
            rewritten.append(arg)
    if _DIRECT_SELECTION:
        rewritten.append(str(REGRESSION_MODULE))
        config.args = rewritten

    if config.getoption("--update-benchmarks") and config.getoption("--nprocs") \
            and not config.getoption("--allow-parallel-update"):
        raise pytest.UsageError(
            "--update-benchmarks with --nprocs is refused by default: references should be "
            "generated by a deterministic serial run, because MPI runs can differ in "
            "ordering and in the low-order digits. Pass --allow-parallel-update if you are "
            "sure."
        )


# --- discovery ---------------------------------------------------------------------------

def pytest_generate_tests(metafunc):
    if "case" not in metafunc.fixturenames:
        return
    cases = discover_cases(TESTS_DIR)
    if _DIRECT_SELECTION:
        wanted = set(_DIRECT_SELECTION)
        cases = [c for c in cases if c.name in wanted]

    params = []
    for case in cases:
        marks = [getattr(pytest.mark, marker) for marker in case.markers]
        if case.status == "xfail":
            marks.append(pytest.mark.xfail(reason=case.status_reason, strict=False))
        # Keep a test and everything it depends on together, so -n auto cannot split a
        # dependency chain across workers. pytest-xdist is optional, and it is the plugin
        # that registers this marker, so only apply it when the plugin is loaded --
        # otherwise --strict-markers rejects it and nothing is collected at all.
        if metafunc.config.pluginmanager.hasplugin("xdist"):
            group = case.depends_on[0] if case.depends_on else case.name
            marks.append(pytest.mark.xdist_group(name=group))
        params.append(pytest.param(case, marks=marks, id=case.name))

    metafunc.parametrize("case", params)


# --- fixtures ----------------------------------------------------------------------------

@pytest.fixture(scope="session")
def profiles():
    return load_profiles(PROFILES_FILE)


@pytest.fixture(scope="session")
def executables(pytestconfig):
    return resolve_executables(
        TEST_SUITE,
        wannier90=pytestconfig.getoption("--wannier90-exe"),
        postw90=pytestconfig.getoption("--postw90-exe"),
        w90chk2chk=pytestconfig.getoption("--w90chk2chk-exe"),
    )


@pytest.fixture(scope="session")
def run_options(pytestconfig):
    return RunOptions(
        nprocs=pytestconfig.getoption("--nprocs") or None,
        launcher=pytestconfig.getoption("--mpi-launcher"),
    )


@pytest.fixture
def work_dir(request, tmp_path, pytestconfig):
    """Where this test runs.  Never the source tree."""
    name = request.node.callspec.id
    explicit = pytestconfig.getoption("--workdir")
    if explicit:
        path = Path(explicit).expanduser().resolve() / name
        if path.exists():
            shutil.rmtree(path)
        path.mkdir(parents=True)
        return path
    # pytest keeps the last three tmp_path roots, which is exactly the post-mortem window
    # we want; --keep-workdir is implied by --workdir and otherwise unnecessary.
    return tmp_path / name


@pytest.fixture(scope="session")
def dependency_artifacts(tmp_path_factory, profiles, executables, run_options):
    """Run-on-demand cache of tests that other tests consume artefacts from.

    Only checkpoint1_read uses this, for the copper.chk that checkpoint0_write produces.
    The old Makefile symlinked the sibling source directory, which worked only because
    tests ran in-tree, in order, and after a full run.
    """
    cache: dict[str, Path] = {}

    def resolve(name: str) -> Path:
        if name in cache:
            return cache[name]
        from w90testlib.case import load_case
        case = load_case(TESTS_DIR / name)
        work = tmp_path_factory.mktemp(f"dependency-{name}-")
        results = execute_case(case, profiles[case.profile], executables, work, run_options)
        failed = [r for r in results if r.returncode != 0]
        if failed and not case.expect_failure:
            raise RuntimeError(
                f"dependency {name!r} failed with exit code {failed[0].returncode}; "
                f"see {work}"
            )
        cache[name] = work
        return work

    return resolve


# --- reporting ---------------------------------------------------------------------------

def pytest_terminal_summary(terminalreporter, exitstatus, config):
    """After --update-benchmarks, say what actually moved."""
    if not config.getoption("--update-benchmarks"):
        return
    updates = config.stash.get(UPDATED_BENCHMARKS, {})
    changed = sorted(name for name, did in updates.items() if did)
    unchanged = sorted(name for name, did in updates.items() if not did)
    failed = len(terminalreporter.stats.get("failed", []))
    errors = len(terminalreporter.stats.get("error", []))

    terminalreporter.write_sep("=", "benchmark update summary")
    terminalreporter.write_line(f"updated:   {len(changed)}")
    for name in changed:
        terminalreporter.write_line(f"  {name}")
    terminalreporter.write_line(f"unchanged: {len(unchanged)}")
    terminalreporter.write_line(f"failed to run: {failed + errors}")
    if changed:
        terminalreporter.write_line("")
        terminalreporter.write_line("Review with: git diff --stat -- test-suite/tests")
