!-*- mode: F90 -*-!
!------------------------------------------------------------!
! Copyright (C) 2012 Daniel Aberg                            !
! Copyright (C) 2026 Wannier Developer Group                 !
!                                                            !
! This library is free software; you can redistribute it     !
! and/or modify it under the terms of the GNU Lesser General !
! Public License as published by the Free Software           !
! Foundation; either version 2.1 of the License, or (at your !
! option) any later version.                                 !
!                                                            !
! This library is distributed in the hope that it will be    !
! useful,but WITHOUT ANY WARRANTY; without even the implied  !
! warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    !
! PURPOSE.  See the GNU Lesser General Public License for    !
! more details.                                              !
!                                                            !
! You should have received a copy of the GNU Lesser General  !
! Public License along with this library; if not, see        !
! <https://www.gnu.org/licenses/>.                           !
!                                                            !
! The webpage of the Wannier90 code is                       !
! <https://www.wannier.org>.                                 !
!                                                            !
! The Wannier90 code is hosted on GitHub                     !
! <https://github.com/wannier-developers/wannier90>          !
!------------------------------------------------------------!
! Code to enable use of the POV-Ray ray-tracing software for !
! the rendering of Wannier function isosurfaces from .xsf    !
! files generated by Wannier90.                              !
!------------------------------------------------------------!
module general

  implicit none

  integer, parameter   :: q = kind(1.0d0)
  real(q), parameter   :: pi = 3.1415926536_q, tpi = 2.0_q*pi
  real(q), parameter   :: zero = 0.0_q
  complex(q), parameter :: czero = cmplx(0.0_q, 0.0_q, kind=q)
contains

  !-----------------------------------------------

  function upcase(string) result(upper)
    character(len=*), intent(in) :: string
    character(len=len(string))   :: upper
    integer :: j
    do j = 1, len(string)
      if (string(j:j) >= "a" .and. string(j:j) <= "z") then
        upper(j:j) = achar(iachar(string(j:j)) - 32)
      else
        upper(j:j) = string(j:j)
      end if
    end do
  end function upcase

end module general
