!-*- mode: F90 -*-!
!                                                            !
! Copyright (C) 2012 Daniel Aberg                            !
!                                                            !
!------------------------------------------------------------!
! This file is distributed as part of the Wannier90 code and !
! under the terms of the                                     !
!                                                            !
!      GNU Lesser General Public License, version 2.1        !
!                                                            !
! see file `LICENSE' in the root directory of the Wannier90  !
! distribution or https://www.gnu.org/licenses/lgpl-2.1.html !
!                                                            !
! The webpage of the Wannier90 code is www.wannier.org       !
!                                                            !
! The Wannier90 code is hosted on GitHub                     !
! https://github.com/wannier-developers/wannier90            !
!------------------------------------------------------------!
! Code to enable use of the POV-Ray ray-tracing software for !
! the rendering of Wannier function isosurfaces from .xsf    !
! files generated by Wannier90.                              !
!------------------------------------------------------------!
program wannierPro

  use m_driver
  implicit none

  print *
  print 1000
  print '(" w90pov")'
  print 1000
  call driver
  print *
  print '("That''s all folks!")'
  print *

1000 format(66('='))

  !-------------------------------------------

end program wannierPro
