!-*- mode: F90 -*-!
!                                                            !
! Copyright (C) 2012 Daniel Aberg                            !
!                                                            !
! This file is distributed under the terms of the GNU        !
! General Public License. See the file `LICENSE' in          !
! the root directory of the present distribution, or         !
! http://www.gnu.org/copyleft/gpl.txt .                      !
!                                                            !
!------------------------------------------------------------!
! Code to enable use of the POV-Ray ray-tracing software for !
! the rendering of Wannier function isosurfaces from .xsf    !
! files generated by Wannier90.                              !
!------------------------------------------------------------!
program wannierPro

  use m_driver
  implicit none

  print *
  print 1000
  print '(" w90pov")'
  print 1000
  call driver
  print *
  print '("That''s all folks!")'
  print *

1000 format(66('='))

  !-------------------------------------------

end program wannierPro
