# -*- MakeFile -*- 
#  Should be no need to change below this line
#

include ../../make.inc

# Contains definition of OBJS, OBJS_POST, LIBRARY, DYNLIBRARY
include ../Makefile.header

POSTDIR = ../postw90/

ifdef COMMS
COMMS := $(strip $(COMMS))
else
COMMS = serial
endif

ifeq ($(COMMS),mpi08)
TEMP1 = -DMPI -DMPI08
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpih)
TEMP1 = -DMPI -DMPIH
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpi90)
TEMP1 = -DMPI -DMPI90
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpi)
# default to f90 style "use mpi"
TEMP1 = -DMPI -DMPI90
TEMP2 = $(MPIF90)
else
TEMP1 =
TEMP2 = $(F90)
endif


wannier libs dynlibs w90chk2chk w90spn2spn: POSTOPTS = $(TEMP1)
wannier libs dynlibs w90chk2chk w90spn2spn: COMPILER = $(TEMP2)
wannier: ../../wannier90.x 
w90chk2chk: ../../w90chk2chk.x
w90spn2spn: ../../w90spn2spn.x

../../w90chk2chk.x: $(OBJS) ../w90chk2chk.F90
	$(COMPILER) $(POSTOPTS) $(FCOPTS) ../w90chk2chk.F90 $(LDOPTS) $(OBJS) $(LIBS) -o ../../w90chk2chk.x

../../w90spn2spn.x: $(OBJS) ../w90spn2spn.F90
	$(COMPILER) $(POSTOPTS) $(FCOPTS) ../w90spn2spn.F90 $(LDOPTS) $(OBJS) $(LIBS) -o ../../w90spn2spn.x

../../wannier90.x: $(LIBRARYV2) ../wannier_prog.F90
	$(COMPILER) $(POSTOPTS) $(FCOPTS)  ../wannier_prog.F90 $(LDOPTS) $(LIBRARYV2) $(LIBS) -o ../../wannier90.x

$(LIBRARYV2): $(OBJS)
	$(AR) $(ARFLAGS) $(LIBRARYV2) $(OBJS)
        
post: POSTOPTS = $(TEMP1)
post: COMPILER = $(TEMP2)
post: mpi_test ../../postw90.x

../../postw90.x: $(OBJS_POST) $(POSTDIR)postw90.F90
	$(COMPILER) $(POSTOPTS) $(FCOPTS) $(POSTDIR)postw90.F90 $(LDOPTS) $(OBJS_POST) $(LIBS) -o ../../postw90.x

mpi_test :
ifeq ($(COMMS),mpi)

ifndef MPIF90

	$(info  ) \
	$(info ********************* STOP **********************) \
	$(info *  COMMS=mpi but MPIF90 is not set in make.inc  *) \
	$(info *  Set MPIF90 to your parallel fortran compiler *) \
	$(info *  On many systems MPIF90=mpif90 will work      *) \
	$(info ********************* STOP **********************) \
	$(info  ) \
	$(error MPIF90 is not set) 

endif

endif 



libs: $(LIBRARY) $(LIBRARYV2)

dynlibs: $(DYNLIBRARY)

$(LIBRARY): $(OBJS) $(OBJS_LIBV1)
	$(AR) $(ARFLAGS) $(LIBRARY) $(OBJS) $(OBJS_LIBV1)

$(DYNLIBRARY): $(OBJS) $(OBJS) $(OBJS_LIBV1)
	echo $(COMPILER)
	$(COMPILER) $(SHAREDLIBFLAGS) $(POSTOPTS) $(LDOPTS) $(OBJS) $(OBJS_LIBV1) $(LIBS) -o $@

clean:
	rm -f *.o *.mod *.MOD *.obj

library_interface.o :  \
	comms.o constants.o error_base.o io.o kmesh.o overlap.o plot.o transport.o \
	types.o wannier90_readwrite.o wannier90_types.o wannierise.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../library_interface.F90

constants.o: ../constants.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../constants.F90

io.o: ../io.F90 types.o constants.o error.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../io.F90

utility.o: ../utility.F90 constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../utility.F90

wannier90_types.o: ../wannier90_types.F90 constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannier90_types.F90

wannier90_readwrite.o: ../wannier90_readwrite.F90 constants.o io.o types.o wannier90_types.o readwrite.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannier90_readwrite.F90

readwrite.o: ../readwrite.F90 types.o constants.o io.o utility.o comms.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../readwrite.F90

types.o: ../types.F90 constants.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../types.F90

hamiltonian.o: ../hamiltonian.F90 ws_distance.o constants.o io.o utility.o types.o wannier90_types.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../hamiltonian.F90

overlap.o: ../overlap.F90 constants.o io.o utility.o types.o sitesym.o wannier90_types.o comms.o error.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../overlap.F90

kmesh.o: ../kmesh.F90 constants.o io.o utility.o types.o 
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../kmesh.F90

error_base.o: ../error_base.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../error_base.F90

error.o: ../error.F90 error_base.o comms.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../error.F90

disentangle.o: ../disentangle.F90 constants.o io.o types.o sitesym.o comms.o wannier90_types.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../disentangle.F90

wannierise.o: ../wannierise.F90 hamiltonian.o constants.o io.o utility.o types.o sitesym.o comms.o wannier90_types.o wannier90_readwrite.o error.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannierise.F90

plot.o: ../plot.F90 constants.o io.o utility.o types.o hamiltonian.o ws_distance.o wannier90_types.o comms.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../plot.F90

ws_distance.o: ../ws_distance.F90 constants.o io.o types.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../ws_distance.F90

transport.o: ../transport.F90 constants.o io.o types.o hamiltonian.o wannier90_types.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../transport.F90

sitesym.o : ../sitesym.F90 utility.o types.o constants.o wannier90_types.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../sitesym.F90

comms.o: ../comms.F90 constants.o error_base.o ../../make.inc
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../comms.F90

boltzwann.o: $(POSTDIR)boltzwann.F90 constants.o types.o io.o utility.o postw90_common.o get_oper.o wan_ham.o comms.o spin.o dos.o postw90_types.o ws_distance.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)boltzwann.F90

geninterp.o: $(POSTDIR)geninterp.F90 constants.o types.o io.o get_oper.o postw90_common.o comms.o utility.o wan_ham.o postw90_types.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)geninterp.F90

get_oper.o: $(POSTDIR)get_oper.F90 types.o constants.o comms.o postw90_common.o io.o utility.o postw90_types.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)get_oper.F90

spin.o: $(POSTDIR)spin.F90 comms.o types.o constants.o utility.o postw90_common.o get_oper.o io.o wan_ham.o postw90_types.o ws_distance.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)spin.F90

dos.o: $(POSTDIR)dos.F90 comms.o types.o postw90_types.o constants.o utility.o io.o wan_ham.o postw90_common.o get_oper.o spin.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)dos.F90

kpath.o: $(POSTDIR)kpath.F90 comms.o types.o constants.o io.o spin.o berry.o postw90_types.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kpath.F90

kslice.o: $(POSTDIR)kslice.F90 comms.o types.o constants.o io.o spin.o berry.o postw90_types.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kslice.F90

berry.o: $(POSTDIR)berry.F90 comms.o types.o constants.o utility.o postw90_common.o get_oper.o io.o spin.o wan_ham.o postw90_types.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)berry.F90

gyrotropic.o: $(POSTDIR)gyrotropic.F90 comms.o types.o constants.o utility.o postw90_common.o get_oper.o io.o spin.o wan_ham.o berry.o postw90_types.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)gyrotropic.F90

wan_ham.o: $(POSTDIR)wan_ham.F90 types.o postw90_types.o constants.o utility.o postw90_common.o get_oper.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)wan_ham.F90

postw90_common.o: $(POSTDIR)postw90_common.F90 postw90_types.o ws_distance.o comms.o types.o utility.o constants.o io.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_common.F90

postw90_types.o: $(POSTDIR)postw90_types.F90 comms.o types.o utility.o constants.o io.o 
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_types.F90

postw90_readwrite.o: $(POSTDIR)postw90_readwrite.F90 comms.o postw90_types.o types.o utility.o constants.o io.o error.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_readwrite.F90

wannier_lib.o: ./constants.o ./io.o ./utility.o ./types.o \
	./hamiltonian.o ./kmesh.o ./overlap.o ./disentangle.o \
	./wannierise.o ./plot.o ./transport.o ./wannier90_types.o \
	./wannier90_readwrite.o ../wannier_lib.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannier_lib.F90


.PHONY: wannier libs post clean mpi_test w90spn2spn

