# -*- MakeFile -*- 
#  Should be no need to change below this line
#

include ../../make.inc

OBJS  =  constants.o io.o utility.o parameters.o hamiltonian.o overlap.o \
	 kmesh.o disentangle.o ws_distance.o wannierise.o plot.o transport.o sitesym.o

OBJS2  =  wannier_lib.o

OBJS_POST  = ws_distance.o parameters.o kmesh.o io.o comms.o utility.o get_oper.o constants.o \
             postw90_common.o wan_ham.o spin.o dos.o berry.o kpath.o kslice.o boltzwann.o geninterp.o

LIBRARY = ../../libwannier.a

POSTDIR = ../postw90/

ifdef COMMS
COMMS := $(strip $(COMMS))
else
COMMS = serial
endif

ifeq ($(COMMS),mpi)
TEMP1 = -DMPI
TEMP2 = $(MPIF90)
else
TEMP1 =
TEMP2 = $(F90)
endif


wannier libs w90chk2chk serialobjs: POSTOPTS = 
wannier libs w90chk2chk serialobjs: COMPILER = $(F90)
wannier: ../../wannier90.x 
w90chk2chk: ../../w90chk2chk.x

serialobjs: $(OBJS)

../../w90chk2chk.x: $(OBJS) ../w90chk2chk.F90
	$(COMPILER) ../w90chk2chk.F90 $(LDOPTS) $(OBJS) $(LIBS) -o ../../w90chk2chk.x

../../wannier90.x: $(OBJS) ../wannier_prog.F90
	$(COMPILER) ../wannier_prog.F90 $(LDOPTS) $(OBJS) $(LIBS) -o ../../wannier90.x

post: POSTOPTS = $(TEMP1)
post: COMPILER = $(TEMP2)
post: mpi_test ../../postw90.x

../../postw90.x: $(OBJS_POST) $(POSTDIR)postw90.F90
	$(COMPILER) $(POSTDIR)postw90.F90 $(POSTOPTS) $(LDOPTS) $(OBJS_POST) $(LIBS) -o ../../postw90.x

mpi_test :
ifeq ($(COMMS),mpi)

ifndef MPIF90

	$(info  ) \
	$(info ********************* STOP **********************) \
	$(info *  COMMS=mpi but MPIF90 is not set in make.inc  *) \
	$(info *  Set MPIF90 to your parallel fortran compiler *) \
	$(info *  On many systems MPIF90=mpif90 will work      *) \
	$(info ********************* STOP **********************) \
	$(info  ) \
	$(error MPIF90 is not set) 

endif

endif 



libs:     $(LIBRARY)

$(LIBRARY): $(OBJS) $(OBJS2) 
	$(AR) $(ARFLAGS) $(LIBRARY) $(OBJS2) $(OBJS)

clean:
	rm -f *.o *.mod *.MOD *.obj

constants.o: ../constants.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../constants.F90

io.o: ../io.F90 constants.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../io.F90

utility.o: ../utility.F90  constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../utility.F90

parameters.o: ../parameters.F90 constants.o io.o utility.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../parameters.F90

hamiltonian.o: ../hamiltonian.F90 ws_distance.o constants.o io.o utility.o parameters.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../hamiltonian.F90

overlap.o: ../overlap.F90 constants.o io.o utility.o parameters.o sitesym.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../overlap.F90

kmesh.o: ../kmesh.F90 constants.o io.o utility.o parameters.o 
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../kmesh.F90

disentangle.o: ../disentangle.F90 constants.o io.o parameters.o sitesym.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../disentangle.F90

wannierise.o: ../wannierise.F90 hamiltonian.o constants.o io.o utility.o parameters.o sitesym.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannierise.F90

plot.o: ../plot.F90 constants.o io.o utility.o parameters.o hamiltonian.o ws_distance.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../plot.F90

ws_distance.o: ../ws_distance.F90 constants.o io.o parameters.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../ws_distance.F90

transport.o: ../transport.F90 constants.o io.o parameters.o hamiltonian.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../transport.F90

sitesym.o : ../sitesym.F90 utility.o parameters.o constants.o 
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../sitesym.F90

comms.o: $(POSTDIR)comms.F90 constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)comms.F90

boltzwann.o: $(POSTDIR)boltzwann.F90 constants.o parameters.o io.o utility.o postw90_common.o get_oper.o wan_ham.o comms.o spin.o dos.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)boltzwann.F90

geninterp.o: $(POSTDIR)geninterp.F90 constants.o parameters.o io.o get_oper.o postw90_common.o comms.o utility.o wan_ham.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)geninterp.F90

get_oper.o: $(POSTDIR)get_oper.F90 parameters.o constants.o comms.o postw90_common.o io.o utility.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)get_oper.F90

spin.o: $(POSTDIR)spin.F90 comms.o parameters.o constants.o utility.o postw90_common.o get_oper.o io.o wan_ham.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)spin.F90

dos.o: $(POSTDIR)dos.F90 comms.o parameters.o constants.o utility.o io.o wan_ham.o postw90_common.o get_oper.o spin.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)dos.F90

kpath.o: $(POSTDIR)kpath.F90 comms.o parameters.o constants.o io.o spin.o berry.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kpath.F90

kslice.o: $(POSTDIR)kslice.F90 comms.o parameters.o constants.o io.o spin.o berry.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kslice.F90

berry.o: $(POSTDIR)berry.F90 comms.o parameters.o constants.o utility.o postw90_common.o get_oper.o io.o spin.o wan_ham.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)berry.F90

wan_ham.o: $(POSTDIR)wan_ham.F90 parameters.o constants.o utility.o postw90_common.o get_oper.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)wan_ham.F90

postw90_common.o: $(POSTDIR)postw90_common.F90 ws_distance.o comms.o parameters.o utility.o constants.o io.o 
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_common.F90

wannier_lib.o: ./constants.o ./io.o ./utility.o ./parameters.o \
	./hamiltonian.o ./kmesh.o ./overlap.o ./disentangle.o \
	./wannierise.o ./plot.o ./transport.o ../wannier_lib.F90
	 $(COMPILER) $(FCOPTS) -c ../wannier_lib.F90


.PHONY: wannier libs post clean mpi_test serialobjs

