# -*- MakeFile -*- 
#  Should be no need to change below this line
#

include ../../make.inc

# Contains definition of OBJS, OBJSLIB, OBJS_POST, LIBRARY, DYNLIBRARY
include ../Makefile.header

POSTDIR = ../postw90/

ifdef COMMS
COMMS := $(strip $(COMMS))
else
COMMS = serial
endif

ifeq ($(COMMS),mpi08)
TEMP1 = -DMPI -DMPI08
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpih)
TEMP1 = -DMPI -DMPIH
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpi90)
TEMP1 = -DMPI -DMPI90
TEMP2 = $(MPIF90)
else ifeq ($(COMMS),mpi)
# default to f90 style "use mpi"
TEMP1 = -DMPI -DMPI90
TEMP2 = $(MPIF90)
else
TEMP1 =
TEMP2 = $(F90)
endif


wannier libs dynlibs w90chk2chk w90spn2spn: POSTOPTS = $(TEMP1)
wannier libs dynlibs w90chk2chk w90spn2spn: COMPILER = $(TEMP2)
wannier: ../../wannier90.x 
w90chk2chk: ../../w90chk2chk.x
w90spn2spn: ../../w90spn2spn.x

../../w90chk2chk.x: $(OBJSLIB) ../w90chk2chk.F90
	$(F90) ../w90chk2chk.F90 $(LDOPTS) $(OBJSLIB) $(LIBS) -o ../../w90chk2chk.x

../../w90spn2spn.x: $(OBJSLIB) ../w90spn2spn.F90
	$(F90) ../w90spn2spn.F90 $(LDOPTS) $(OBJSLIB) $(LIBS) -o ../../w90spn2spn.x

../../wannier90.x: $(LIBRARYV2) ../wannier_prog.F90
	$(COMPILER) ../wannier_prog.F90 $(POSTOPTS) $(LDOPTS) $(LIBRARYV2) $(LIBS) -o ../../wannier90.x

$(LIBRARYV2): $(OBJS)
	$(AR) $(ARFLAGS) $(LIBRARYV2) $(OBJS)
        
#../../wannier90.x: ../../libwan2.a ../wannier_prog.F90
#	$(COMPILER) ../wannier_prog.F90 $(POSTOPTS) $(LDOPTS) $(LIBRARYV2) $(LIBS) -o ../../wannier90.x
#
#../../libwan2.a: $(OBJS)
#	$(AR) $(ARFLAGS) $(LIBRARYV2) $(OBJS)

post: POSTOPTS = $(TEMP1)
post: COMPILER = $(TEMP2)
post: mpi_test ../../postw90.x

../../postw90.x: $(OBJS_POST) $(POSTDIR)postw90.F90
	$(COMPILER) $(POSTDIR)postw90.F90 $(POSTOPTS) $(LDOPTS) $(OBJS_POST) $(LIBS) -o ../../postw90.x

mpi_test :
ifeq ($(COMMS),mpi)

ifndef MPIF90

	$(info  ) \
	$(info ********************* STOP **********************) \
	$(info *  COMMS=mpi but MPIF90 is not set in make.inc  *) \
	$(info *  Set MPIF90 to your parallel fortran compiler *) \
	$(info *  On many systems MPIF90=mpif90 will work      *) \
	$(info ********************* STOP **********************) \
	$(info  ) \
	$(error MPIF90 is not set) 

endif

endif 



libs: $(LIBRARY) $(LIBRARYV2)

dynlibs: $(DYNLIBRARY)

$(LIBRARY): $(OBJSLIB)
	$(AR) $(ARFLAGS) $(LIBRARY) $(OBJSLIB)

$(DYNLIBRARY): $(OBJS) $(OBJSLIB)
	echo $(COMPILER)
	$(COMPILER) $(SHAREDLIBFLAGS) $(POSTOPTS) $(LDOPTS) $(OBJS) $(OBJSLIB) $(LIBS) -o $@

clean:
	rm -f *.o *.mod *.MOD *.obj

constants.o: ../constants.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../constants.F90

comms-abort-serial.o: ../comms-abort.F90
	$(COMPILER) $(FCOPTS) -c ../comms-abort.F90 -o comms-abort-serial.o

comms-abort.o: ../comms-abort.F90
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../comms-abort.F90

io.o: ../io.F90 constants.o comms-abort.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../io.F90

utility.o: ../utility.F90  constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../utility.F90

wann90_param.o: ../wann90_param.F90 constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wann90_param.F90

wann90_methods.o: ../wann90_methods.F90 constants.o io.o parameters.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wann90_methods.F90

parameters.o: ../parameters.F90 constants.o io.o utility.o comms.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../parameters.F90

hamiltonian.o: ../hamiltonian.F90 ws_distance.o constants.o io.o utility.o parameters.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../hamiltonian.F90

overlap.o: ../overlap.F90 constants.o io.o utility.o parameters.o sitesym.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../overlap.F90

kmesh.o: ../kmesh.F90 constants.o io.o utility.o parameters.o 
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../kmesh.F90

disentangle.o: ../disentangle.F90 constants.o io.o parameters.o sitesym.o comms.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../disentangle.F90

wannierise.o: ../wannierise.F90 hamiltonian.o constants.o io.o utility.o parameters.o sitesym.o comms.o wann90_param.o wann90_methods.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../wannierise.F90

plot.o: ../plot.F90 constants.o io.o utility.o parameters.o hamiltonian.o ws_distance.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../plot.F90

ws_distance.o: ../ws_distance.F90 constants.o io.o parameters.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../ws_distance.F90

transport.o: ../transport.F90 constants.o io.o parameters.o hamiltonian.o wann90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../transport.F90

sitesym.o : ../sitesym.F90 utility.o parameters.o constants.o wann90_param.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../sitesym.F90

comms.o: ../comms.F90 constants.o io.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c ../comms.F90

comms-serial.o: ../comms.F90 constants.o io.o
	$(COMPILER) $(FCOPTS) -c ../comms.F90 -o comms-serial.o

boltzwann.o: $(POSTDIR)boltzwann.F90 constants.o parameters.o io.o utility.o postw90_common.o get_oper.o wan_ham.o comms.o spin.o dos.o postw90_param.o ws_distance.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)boltzwann.F90

geninterp.o: $(POSTDIR)geninterp.F90 constants.o parameters.o io.o get_oper.o postw90_common.o comms.o utility.o wan_ham.o postw90_param.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)geninterp.F90

get_oper.o: $(POSTDIR)get_oper.F90 parameters.o constants.o comms.o postw90_common.o io.o utility.o postw90_param.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)get_oper.F90

spin.o: $(POSTDIR)spin.F90 comms.o parameters.o constants.o utility.o postw90_common.o get_oper.o io.o wan_ham.o postw90_param.o ws_distance.o
	 $(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)spin.F90

dos.o: $(POSTDIR)dos.F90 comms.o parameters.o postw90_param.o constants.o utility.o io.o wan_ham.o postw90_common.o get_oper.o spin.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)dos.F90

kpath.o: $(POSTDIR)kpath.F90 comms.o parameters.o constants.o io.o spin.o berry.o postw90_param.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kpath.F90

kslice.o: $(POSTDIR)kslice.F90 comms.o parameters.o constants.o io.o spin.o berry.o postw90_param.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)kslice.F90

berry.o: $(POSTDIR)berry.F90 comms.o parameters.o constants.o utility.o postw90_common.o get_oper.o io.o spin.o wan_ham.o postw90_param.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)berry.F90

gyrotropic.o: $(POSTDIR)gyrotropic.F90 comms.o parameters.o constants.o utility.o postw90_common.o get_oper.o io.o spin.o wan_ham.o berry.o postw90_param.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)gyrotropic.F90

wan_ham.o: $(POSTDIR)wan_ham.F90 parameters.o postw90_param.o constants.o utility.o postw90_common.o get_oper.o ws_distance.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)wan_ham.F90

postw90_common.o: $(POSTDIR)postw90_common.F90 postw90_param.o ws_distance.o comms.o parameters.o utility.o constants.o io.o
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_common.F90

postw90_param.o: $(POSTDIR)postw90_param.F90 comms.o parameters.o utility.o constants.o io.o 
	$(COMPILER) $(POSTOPTS) $(FCOPTS) -c $(POSTDIR)postw90_param.F90

wannier_lib.o: ./constants.o ./io.o ./utility.o ./parameters.o \
	./hamiltonian.o ./kmesh.o ./overlap.o ./disentangle.o \
	./wannierise.o ./plot.o ./transport.o ./wann90_param.o \
	./wann90_methods.o ../wannier_lib.F90
	 $(COMPILER) $(FCOPTS) -c ../wannier_lib.F90


.PHONY: wannier libs post clean mpi_test w90spn2spn

